<form method="post" action="{{url('vin/discs/add')}}" class="form-horizontal">
    <fieldset>
    {{csrf_field()}}
    <!-- Form Name -->
        <legend>Заявка на подбор дисков</legend>

        <div class="form-group">
            <label class="col-md-4 control-label" for="tyre_width">Vin-code</label>
            <div class="col-md-4">
                @isset($vinrequestlist)
                    @if (count($vinrequestlist)>0)
                        <select name="vinrequest_id" id="vinrequest_id" class="form-control">
                            @foreach($vinrequestlist as $vin)
                                <option value="{{$vin->id}}">{{$vin->vincode}}</option>
                            @endforeach
                        </select>
                    @else
                        <a href="#vinPanel" class="btn btn-info open-vin-tab">Создать Vin-запрос</a>

                    @endif
                @endisset
            </div>
        </div>
        <!-- Select Basic -->
        <div class="form-group">
            <label class="col-md-4 control-label" for="disc_width">Ширина диска</label>
            <div class="col-md-4">
                <select id="disc_width" name="disc_width" class="form-control">
                    <option value="-1">не выбрана</option>
                    <option value="3" >3</option>
                    <option value="3.5" >3.5</option>
                    <option value="4" >4</option>
                    <option value="4.5" >4.5</option>
                    <option value="5" >5</option>
                    <option value="5.25" >5.25</option>
                    <option value="5.5" >5.5</option>
                    <option value="5.51" >5.51</option>
                    <option value="6" >6</option>
                    <option value="6.5" >6.5</option>
                    <option value="6.75" >6.75</option>
                    <option value="7" >7</option>
                    <option value="7.25" >7.25</option>
                    <option value="7.5" >7.5</option>
                    <option value="8" >8</option>
                    <option value="8.25" >8.25</option>
                    <option value="8.5" >8.5</option>
                    <option value="8.75" >8.75</option>
                    <option value="9" >9</option>
                    <option value="9.5" >9.5</option>
                    <option value="9.9" >9.9</option>
                    <option value="10" >10</option>
                    <option value="10.25" >10.25</option>
                    <option value="10.5" >10.5</option>
                    <option value="10.75" >10.75</option>
                    <option value="11" >11</option>
                    <option value="11.25" >11.25</option>
                    <option value="11.5" >11.5</option>
                    <option value="11.75" >11.75</option>
                    <option value="12" >12</option>
                    <option value="13" >13</option>
                    <option value="14" >14</option>

                </select>

                </select>
            </div>
        </div>

        <!-- Select Basic -->
        <div class="form-group">
            <label class="col-md-4 control-label" for="diameter">Диаметр</label>
            <div class="col-md-4">
                <select id="diameter" name="diameter" class="form-control">
                    <option value="-1">не выбрано</option>
                    <option value="12" >12</option>
                    <option value="13" >13</option>
                    <option value="14" >14</option>
                    <option value="15" >15</option>
                    <option value="16" >16</option>
                    <option value="17" >17</option>
                    <option value="17.5" >17.5</option>
                    <option value="18" >18</option>
                    <option value="19" >19</option>
                    <option value="19.5" >19.5</option>
                    <option value="20" >20</option>
                    <option value="21" >21</option>
                    <option value="22" >22</option>
                    <option value="22.5" >22.5</option>
                    <option value="23" >23</option>
                    <option value="24" >24</option>
                    <option value="25" >25</option>
                    <option value="26" >26</option>
                    <option value="28" >28</option>


                </select>
            </div>
        </div>

        <!-- Select Basic -->
        <div class="form-group">
            <label class="col-md-4 control-label" for="radius">Вылет</label>
            <div class="col-md-4">
                <select id="radius" name="radius" class="form-control">
                    <option value="-1">не выбрано</option>
                    <option value="1" >1</option>
                    <option value="2" >2</option>
                    <option value="3" >3</option>
                    <option value="4" >4</option>
                    <option value="5" >5</option>
                    <option value="6" >6</option>
                    <option value="7" >7</option>
                    <option value="8" >8</option>
                    <option value="8.60" >8.60</option>
                    <option value="9" >9</option>
                    <option value="10" >10</option>
                    <option value="11" >11</option>
                    <option value="12" >12</option>
                    <option value="12.50" >12.50</option>
                    <option value="13" >13</option>
                    <option value="14" >14</option>
                    <option value="15" >15</option>
                    <option value="15.50" >15.50</option>
                    <option value="16" >16</option>
                    <option value="17" >17</option>
                    <option value="18" >18</option>
                    <option value="19" >19</option>
                    <option value="20" >20</option>
                    <option value="20.50" >20.50</option>
                    <option value="21" >21</option>
                    <option value="22" >22</option>
                    <option value="23" >23</option>
                    <option value="23.50" >23.50</option>
                    <option value="24" >24</option>
                    <option value="25" >25</option>
                    <option value="26" >26</option>
                    <option value="27" >27</option>
                    <option value="27.30" >27.30</option>
                    <option value="28" >28</option>
                    <option value="28.50" >28.50</option>
                    <option value="29" >29</option>
                    <option value="30" >30</option>
                    <option value="30.50" >30.50</option>
                    <option value="31" >31</option>
                    <option value="31.50" >31.50</option>
                    <option value="32" >32</option>
                    <option value="33" >33</option>
                    <option value="34" >34</option>
                    <option value="34.50" >34.50</option>
                    <option value="35" >35</option>
                    <option value="36" >36</option>
                    <option value="36.50" >36.50</option>
                    <option value="37" >37</option>
                    <option value="37.50" >37.50</option>
                    <option value="38" >38</option>
                    <option value="38.80" >38.80</option>
                    <option value="39" >39</option>
                    <option value="39.50" >39.50</option>
                    <option value="39.80" >39.80</option>
                    <option value="40" >40</option>
                    <option value="40.50" >40.50</option>
                    <option value="40.75" >40.75</option>
                    <option value="41" >41</option>
                    <option value="41.30" >41.30</option>
                    <option value="41.50" >41.50</option>
                    <option value="42" >42</option>
                    <option value="43" >43</option>
                    <option value="43.50" >43.50</option>
                    <option value="43.80" >43.80</option>
                    <option value="44" >44</option>
                    <option value="45" >45</option>
                    <option value="45.10" >45.10</option>
                    <option value="45.20" >45.20</option>
                    <option value="45.50" >45.50</option>
                    <option value="45.70" >45.70</option>
                    <option value="46" >46</option>
                    <option value="47" >47</option>
                    <option value="47.50" >47.50</option>
                    <option value="48" >48</option>
                    <option value="48.50" >48.50</option>
                    <option value="49" >49</option>
                    <option value="49.50" >49.50</option>
                    <option value="50" >50</option>
                    <option value="50.50" >50.50</option>
                    <option value="50.80" >50.80</option>
                    <option value="51" >51</option>
                    <option value="52" >52</option>
                    <option value="52.20" >52.20</option>
                    <option value="52.50" >52.50</option>
                    <option value="52.60" >52.60</option>
                    <option value="53" >53</option>
                    <option value="54" >54</option>
                    <option value="54.10" >54.10</option>
                    <option value="55" >55</option>
                    <option value="56" >56</option>
                    <option value="56.10" >56.10</option>
                    <option value="56.40" >56.40</option>
                    <option value="56.60" >56.60</option>
                    <option value="57" >57</option>
                    <option value="57.10" >57.10</option>
                    <option value="58" >58</option>
                    <option value="58.60" >58.60</option>
                    <option value="59" >59</option>
                    <option value="60" >60</option>
                    <option value="60.10" >60.10</option>
                    <option value="62" >62</option>
                    <option value="63" >63</option>
                    <option value="63.30" >63.30</option>
                    <option value="63.40" >63.40</option>
                    <option value="64" >64</option>
                    <option value="65" >65</option>
                    <option value="65.10" >65.10</option>
                    <option value="66" >66</option>
                    <option value="66.60" >66.60</option>
                    <option value="67" >67</option>
                    <option value="67.10" >67.10</option>
                    <option value="68" >68</option>
                    <option value="69.10" >69.10</option>
                    <option value="70" >70</option>
                    <option value="71.60" >71.60</option>
                    <option value="72" >72</option>
                    <option value="72.20" >72.20</option>
                    <option value="72.60" >72.60</option>
                    <option value="73.10" >73.10</option>
                    <option value="73.20" >73.20</option>
                    <option value="74.10" >74.10</option>
                    <option value="75" >75</option>
                    <option value="83" >83</option>
                    <option value="87.10" >87.10</option>
                    <option value="99.90" >99.90</option>
                    <option value="102" >102</option>
                    <option value="105" >105</option>
                    <option value="105.50" >105.50</option>
                    <option value="106" >106</option>
                    <option value="107" >107</option>
                    <option value="108" >108</option>
                    <option value="110" >110</option>
                    <option value="110.10" >110.10</option>
                    <option value="112" >112</option>
                    <option value="114" >114</option>
                    <option value="115" >115</option>
                    <option value="120" >120</option>
                    <option value="121.50" >121.50</option>
                    <option value="122" >122</option>
                    <option value="122.50" >122.50</option>
                    <option value="123" >123</option>
                    <option value="125" >125</option>
                    <option value="126" >126</option>
                    <option value="128" >128</option>
                    <option value="128.50" >128.50</option>
                    <option value="129" >129</option>
                    <option value="132" >132</option>
                    <option value="132.50" >132.50</option>
                    <option value="134" >134</option>
                    <option value="135" >135</option>
                    <option value="135.50" >135.50</option>
                    <option value="140" >140</option>
                    <option value="142" >142</option>
                    <option value="143" >143</option>
                    <option value="147" >147</option>
                    <option value="149" >149</option>
                    <option value="150" >150</option>
                    <option value="152" >152</option>
                    <option value="153" >153</option>
                    <option value="156" >156</option>
                    <option value="157" >157</option>
                    <option value="161" >161</option>
                    <option value="163" >163</option>
                    <option value="165" >165</option>
                    <option value="175" >175</option>
                    <option value="220" >220</option>

                </select>
            </div>
        </div>

        <!-- Select Basic -->
        <div class="form-group">
            <label class="col-md-4 control-label" for="holes">Отверстий</label>
            <div class="col-md-4">
                <select id="holes" name="holes" class="form-control">
                    <option value="-1">не выбрано</option>
                    <option value="3" >3</option>
                    <option value="4" >4</option>
                    <option value="5" >5</option>
                    <option value="6" >6</option>
                    <option value="8" >8</option>
                    <option value="9" >9</option>
                    <option value="10" >10</option>

                </select>
            </div>
        </div>


        <!-- Select Basic -->
        <div class="form-group">
            <label class="col-md-4 control-label" for="pcd">PCD</label>
            <div class="col-md-4">
                <select id="pcd" name="pcd" class="form-control">
                    <option value="-1">не выбрано</option>
                    <option value="98" >98</option>
                    <option value="100" >100</option>
                    <option value="105" >105</option>
                    <option value="107.95" >107.95</option>
                    <option value="108" >108</option>
                    <option value="110" >110</option>
                    <option value="112" >112</option>
                    <option value="114" >114</option>
                    <option value="114.3" >114.3</option>
                    <option value="115" >115</option>
                    <option value="118" >118</option>
                    <option value="120" >120</option>
                    <option value="120.6" >120.6</option>
                    <option value="120.65" >120.65</option>
                    <option value="120.7" >120.7</option>
                    <option value="125" >125</option>
                    <option value="127" >127</option>
                    <option value="130" >130</option>
                    <option value="130.65" >130.65</option>
                    <option value="135" >135</option>
                    <option value="139" >139</option>
                    <option value="139.1" >139.1</option>
                    <option value="139.7" >139.7</option>
                    <option value="150" >150</option>
                    <option value="160" >160</option>
                    <option value="161" >161</option>
                    <option value="165" >165</option>
                    <option value="165.1" >165.1</option>
                    <option value="170" >170</option>
                    <option value="175" >175</option>
                    <option value="180" >180</option>
                    <option value="189" >189</option>
                    <option value="190" >190</option>
                    <option value="199" >199</option>
                    <option value="200" >200</option>
                    <option value="205" >205</option>
                    <option value="208" >208</option>
                    <option value="210" >210</option>
                    <option value="220" >220</option>
                    <option value="222.25" >222.25</option>
                    <option value="222.5" >222.5</option>
                    <option value="225" >225</option>
                    <option value="245" >245</option>
                    <option value="256" >256</option>
                    <option value="275" >275</option>
                    <option value="285" >285</option>
                    <option value="285.75" >285.75</option>
                    <option value="335" >335</option>

                </select>
            </div>
        </div>

        <!-- Select Basic -->
        <div class="form-group">
            <label class="col-md-4 control-label" for="dco">ДЦО</label>
            <div class="col-md-4">
                <select id="dco" name="dco" class="form-control">
                    <option value="-1">не выбрано</option>
                    <option value="10" >10</option>
                    <option value="15" >15</option>
                    <option value="24" >24</option>
                    <option value="35" >35</option>
                    <option value="37" >37</option>
                    <option value="37.1" >37.1</option>
                    <option value="37.5" >37.5</option>
                    <option value="38" >38</option>
                    <option value="39" >39</option>
                    <option value="40" >40</option>
                    <option value="42" >42</option>
                    <option value="43" >43</option>
                    <option value="45" >45</option>
                    <option value="46" >46</option>
                    <option value="50" >50</option>
                    <option value="51.4" >51.4</option>
                    <option value="52" >52</option>
                    <option value="52.5" >52.5</option>
                    <option value="54" >54</option>
                    <option value="54.1" >54.1</option>
                    <option value="54.5" >54.5</option>
                    <option value="55" >55</option>
                    <option value="55.1" >55.1</option>
                    <option value="55.3" >55.3</option>
                    <option value="55.5" >55.5</option>
                    <option value="56" >56</option>
                    <option value="56.1" >56.1</option>
                    <option value="56.4" >56.4</option>
                    <option value="56.5" >56.5</option>
                    <option value="56.56" >56.56</option>
                    <option value="56.6" >56.6</option>
                    <option value="56.62" >56.62</option>
                    <option value="56.7" >56.7</option>
                    <option value="56.8" >56.8</option>
                    <option value="57" >57</option>
                    <option value="57.06" >57.06</option>
                    <option value="57.1" >57.1</option>
                    <option value="57.32" >57.32</option>
                    <option value="57.6" >57.6</option>
                    <option value="58" >58</option>
                    <option value="58.06" >58.06</option>
                    <option value="58.1" >58.1</option>
                    <option value="58.5" >58.5</option>
                    <option value="58.55" >58.55</option>
                    <option value="58.6" >58.6</option>
                    <option value="58.8" >58.8</option>
                    <option value="59" >59</option>
                    <option value="59.1" >59.1</option>
                    <option value="59.5" >59.5</option>
                    <option value="59.6" >59.6</option>
                    <option value="60" >60</option>
                    <option value="60.1" >60.1</option>
                    <option value="60.2" >60.2</option>
                    <option value="60.4" >60.4</option>
                    <option value="60.5" >60.5</option>
                    <option value="60.8" >60.8</option>
                    <option value="61" >61</option>
                    <option value="61.1" >61.1</option>
                    <option value="61.9" >61.9</option>
                    <option value="63" >63</option>
                    <option value="63.1" >63.1</option>
                    <option value="63.3" >63.3</option>
                    <option value="63.34" >63.34</option>
                    <option value="63.35" >63.35</option>
                    <option value="63.4" >63.4</option>
                    <option value="63.5" >63.5</option>
                    <option value="63.6" >63.6</option>
                    <option value="64" >64</option>
                    <option value="64.1" >64.1</option>
                    <option value="64.5" >64.5</option>
                    <option value="65" >65</option>
                    <option value="65.05" >65.05</option>
                    <option value="65.06" >65.06</option>
                    <option value="65.1" >65.1</option>
                    <option value="65.2" >65.2</option>
                    <option value="65.5" >65.5</option>
                    <option value="65.56" >65.56</option>
                    <option value="65.6" >65.6</option>
                    <option value="66" >66</option>
                    <option value="66.1" >66.1</option>
                    <option value="66.2" >66.2</option>
                    <option value="66.3" >66.3</option>
                    <option value="66.4" >66.4</option>
                    <option value="66.45" >66.45</option>
                    <option value="66.46" >66.46</option>
                    <option value="66.5" >66.5</option>
                    <option value="66.56" >66.56</option>
                    <option value="66.6" >66.6</option>
                    <option value="66.9" >66.9</option>
                    <option value="66.92" >66.92</option>
                    <option value="67" >67</option>
                    <option value="67.04" >67.04</option>
                    <option value="67.1" >67.1</option>
                    <option value="67.13" >67.13</option>
                    <option value="67.14" >67.14</option>
                    <option value="67.2" >67.2</option>
                    <option value="67.7" >67.7</option>
                    <option value="68" >68</option>
                    <option value="68.1" >68.1</option>
                    <option value="69" >69</option>
                    <option value="69.1" >69.1</option>
                    <option value="69.2" >69.2</option>
                    <option value="69.3" >69.3</option>
                    <option value="69.6" >69.6</option>
                    <option value="70" >70</option>
                    <option value="70.02" >70.02</option>
                    <option value="70.1" >70.1</option>
                    <option value="70.2" >70.2</option>
                    <option value="70.27" >70.27</option>
                    <option value="70.28" >70.28</option>
                    <option value="70.3" >70.3</option>
                    <option value="70.4" >70.4</option>
                    <option value="70.5" >70.5</option>
                    <option value="70.6" >70.6</option>
                    <option value="70.64" >70.64</option>
                    <option value="70.7" >70.7</option>
                    <option value="70.8" >70.8</option>
                    <option value="71" >71</option>
                    <option value="71.1" >71.1</option>
                    <option value="71.3" >71.3</option>
                    <option value="71.4" >71.4</option>
                    <option value="71.5" >71.5</option>
                    <option value="71.56" >71.56</option>
                    <option value="71.58" >71.58</option>
                    <option value="71.6" >71.6</option>
                    <option value="71.69" >71.69</option>
                    <option value="72" >72</option>
                    <option value="72.1" >72.1</option>
                    <option value="72.2" >72.2</option>
                    <option value="72.27" >72.27</option>
                    <option value="72.3" >72.3</option>
                    <option value="72.4" >72.4</option>
                    <option value="72.5" >72.5</option>
                    <option value="72.56" >72.56</option>
                    <option value="72.6" >72.6</option>
                    <option value="72.62" >72.62</option>
                    <option value="72.69" >72.69</option>
                    <option value="72.7" >72.7</option>
                    <option value="73" >73</option>
                    <option value="73.06" >73.06</option>
                    <option value="73.1" >73.1</option>
                    <option value="73.13" >73.13</option>
                    <option value="73.14" >73.14</option>
                    <option value="73.2" >73.2</option>
                    <option value="73.6" >73.6</option>
                    <option value="73.7" >73.7</option>
                    <option value="73.8" >73.8</option>
                    <option value="73.9" >73.9</option>
                    <option value="74" >74</option>
                    <option value="74.1" >74.1</option>
                    <option value="74.2" >74.2</option>
                    <option value="74.4" >74.4</option>
                    <option value="74.5" >74.5</option>
                    <option value="75" >75</option>
                    <option value="75.1" >75.1</option>
                    <option value="76" >76</option>
                    <option value="76.1" >76.1</option>
                    <option value="76.5" >76.5</option>
                    <option value="76.9" >76.9</option>
                    <option value="77" >77</option>
                    <option value="77.77" >77.77</option>
                    <option value="77.8" >77.8</option>
                    <option value="77.9" >77.9</option>
                    <option value="78" >78</option>
                    <option value="78.09" >78.09</option>
                    <option value="78.1" >78.1</option>
                    <option value="78.2" >78.2</option>
                    <option value="78.3" >78.3</option>
                    <option value="79" >79</option>
                    <option value="79.1" >79.1</option>
                    <option value="79.5" >79.5</option>
                    <option value="79.6" >79.6</option>
                    <option value="80" >80</option>
                    <option value="80.1" >80.1</option>
                    <option value="82" >82</option>
                    <option value="83" >83</option>
                    <option value="83.3" >83.3</option>
                    <option value="83.7" >83.7</option>
                    <option value="84" >84</option>
                    <option value="84.1" >84.1</option>
                    <option value="84.2" >84.2</option>
                    <option value="85" >85</option>
                    <option value="85.1" >85.1</option>
                    <option value="85.3" >85.3</option>
                    <option value="85.6" >85.6</option>
                    <option value="86.8" >86.8</option>
                    <option value="86.87" >86.87</option>
                    <option value="86.89" >86.89</option>
                    <option value="87" >87</option>
                    <option value="87.1" >87.1</option>
                    <option value="87.2" >87.2</option>
                    <option value="87.5" >87.5</option>
                    <option value="89" >89</option>
                    <option value="89.1" >89.1</option>
                    <option value="92.1" >92.1</option>
                    <option value="92.3" >92.3</option>
                    <option value="92.5" >92.5</option>
                    <option value="92.6" >92.6</option>
                    <option value="92.7" >92.7</option>
                    <option value="93" >93</option>
                    <option value="93.1" >93.1</option>
                    <option value="93.3" >93.3</option>
                    <option value="93.7" >93.7</option>
                    <option value="95" >95</option>
                    <option value="95.1" >95.1</option>
                    <option value="95.3" >95.3</option>
                    <option value="95.35" >95.35</option>
                    <option value="95.4" >95.4</option>
                    <option value="95.5" >95.5</option>
                    <option value="95.6" >95.6</option>
                    <option value="96" >96</option>
                    <option value="98" >98</option>
                    <option value="98.1" >98.1</option>
                    <option value="98.5" >98.5</option>
                    <option value="98.6" >98.6</option>
                    <option value="99.9" >99.9</option>
                    <option value="100" >100</option>
                    <option value="100.1" >100.1</option>
                    <option value="100.2" >100.2</option>
                    <option value="100.3" >100.3</option>
                    <option value="100.5" >100.5</option>
                    <option value="101" >101</option>
                    <option value="101.5" >101.5</option>
                    <option value="101.9" >101.9</option>
                    <option value="102" >102</option>
                    <option value="103" >103</option>
                    <option value="104.1" >104.1</option>
                    <option value="106" >106</option>
                    <option value="106.1" >106.1</option>
                    <option value="106.2" >106.2</option>
                    <option value="106.25" >106.25</option>
                    <option value="106.3" >106.3</option>
                    <option value="106.5" >106.5</option>
                    <option value="106.6" >106.6</option>
                    <option value="106.9" >106.9</option>
                    <option value="107" >107</option>
                    <option value="107.1" >107.1</option>
                    <option value="107.5" >107.5</option>
                    <option value="107.6" >107.6</option>
                    <option value="107.95" >107.95</option>
                    <option value="108" >108</option>
                    <option value="108.1" >108.1</option>
                    <option value="108.2" >108.2</option>
                    <option value="108.3" >108.3</option>
                    <option value="108.4" >108.4</option>
                    <option value="108.5" >108.5</option>
                    <option value="108.6" >108.6</option>
                    <option value="108.7" >108.7</option>
                    <option value="109" >109</option>
                    <option value="109.5" >109.5</option>
                    <option value="109.7" >109.7</option>
                    <option value="109.8" >109.8</option>
                    <option value="110" >110</option>
                    <option value="110.1" >110.1</option>
                    <option value="110.16" >110.16</option>
                    <option value="110.2" >110.2</option>
                    <option value="110.3" >110.3</option>
                    <option value="110.5" >110.5</option>
                    <option value="110.6" >110.6</option>
                    <option value="111" >111</option>
                    <option value="111.1" >111.1</option>
                    <option value="111.2" >111.2</option>
                    <option value="111.5" >111.5</option>
                    <option value="111.6" >111.6</option>
                    <option value="112" >112</option>
                    <option value="112.1" >112.1</option>
                    <option value="112.2" >112.2</option>
                    <option value="112.5" >112.5</option>
                    <option value="112.75" >112.75</option>
                    <option value="113" >113</option>
                    <option value="113.1" >113.1</option>
                    <option value="114" >114</option>
                    <option value="114.3" >114.3</option>
                    <option value="116.7" >116.7</option>
                    <option value="116.9" >116.9</option>
                    <option value="118" >118</option>
                    <option value="120" >120</option>
                    <option value="122.5" >122.5</option>
                    <option value="124" >124</option>
                    <option value="125" >125</option>
                    <option value="125.1" >125.1</option>
                    <option value="127" >127</option>
                    <option value="130" >130</option>
                    <option value="130.1" >130.1</option>
                    <option value="130.2" >130.2</option>
                    <option value="130.8" >130.8</option>
                    <option value="130.81" >130.81</option>
                    <option value="131" >131</option>
                    <option value="138.8" >138.8</option>
                    <option value="139" >139</option>
                    <option value="139.7" >139.7</option>
                    <option value="141" >141</option>
                    <option value="142.1" >142.1</option>
                    <option value="150" >150</option>
                    <option value="160" >160</option>
                    <option value="161" >161</option>
                    <option value="164" >164</option>
                    <option value="168" >168</option>
                    <option value="176" >176</option>
                    <option value="202" >202</option>
                    <option value="220" >220</option>
                    <option value="221" >221</option>
                    <option value="228" >228</option>
                    <option value="281" >281</option>
                    <option value="561" >561</option>
                    <option value="701" >701</option>
                    <option value="716" >716</option>

                </select>
            </div>
        </div>

        <!-- Select Basic -->
        <div class="form-group">
            <label class="col-md-4 control-label" for="type">Тип</label>
            <div class="col-md-4">
                <select id="type" name="type" class="form-control">
                    <option value="-1">не выбрано</option>
                    <option value="кованые" >кованые</option>
                    <option value="литые" >литые</option>
                    <option value="сборные" >сборные</option>
                    <option value="штампованные" >штампованные</option>

                </select>
            </div>
        </div>

        <!-- Select Basic -->
        <div class="form-group">
            <label class="col-md-4 control-label" for="color">Цвет</label>
            <div class="col-md-4">
                <select id="color" name="color" class="form-control">
                    <option value="-1">не выбрано</option>
                    <option value="белый" >белый</option>
                    <option value="белый+красный" >белый+красный</option>
                    <option value="белый+синий" >белый+синий</option>
                    <option value="графит" >графит</option>
                    <option value="желтый" >желтый</option>
                    <option value="зеленый" >зеленый</option>
                    <option value="золотистый" >золотистый</option>
                    <option value="коричневый" >коричневый</option>
                    <option value="красный" >красный</option>
                    <option value="оранжевый" >оранжевый</option>
                    <option value="серебристый" >серебристый</option>
                    <option value="серебристый+бронзовый" >серебристый+бронзовый</option>
                    <option value="серебристый+графит" >серебристый+графит</option>
                    <option value="серебристый+красный" >серебристый+красный</option>
                    <option value="серебристый+синий" >серебристый+синий</option>
                    <option value="серебристый+черный" >серебристый+черный</option>
                    <option value="синий" >синий</option>
                    <option value="хром" >хром</option>
                    <option value="черный" >черный</option>
                    <option value="черный+белый" >черный+белый</option>
                    <option value="черный+желтый" >черный+желтый</option>
                    <option value="черный+красный" >черный+красный</option>
                    <option value="черный+оранжевый" >черный+оранжевый</option>
                    <option value="черный+синий" >черный+синий</option>

                </select>
            </div>
        </div>

        <!-- Select Basic -->
        <div class="form-group">
            <label class="col-md-4 control-label" for="manufacturer">Производитель</label>
            <div class="col-md-4">
                <select id="manufacturer" name="manufacturer" class="form-control">
                    <option value="-1">не выбрано</option>
                    <option value="AC SCHNITZER" >AC SCHNITZER</option>
                    <option value="ACE" >ACE</option>
                    <option value="ADORA" >ADORA</option>
                    <option value="ADVAN" >ADVAN</option>
                    <option value="ADVANTI" >ADVANTI</option>
                    <option value="AEZ" >AEZ</option>
                    <option value="AGFORGED" >AGFORGED</option>
                    <option value="AITL" >AITL</option>
                    <option value="AKITA" >AKITA</option>
                    <option value="ALBA" >ALBA</option>
                    <option value="ALCASTA" >ALCASTA</option>
                    <option value="ALEKS" >ALEKS</option>
                    <option value="ALESSIO" >ALESSIO</option>
                    <option value="ALEX" >ALEX</option>
                    <option value="ALLANTE" >ALLANTE</option>
                    <option value="ALLIED WHEEL" >ALLIED WHEEL</option>
                    <option value="ALLTECH" >ALLTECH</option>
                    <option value="ALSTER" >ALSTER</option>
                    <option value="ALUCHROM" >ALUCHROM</option>
                    <option value="ALUTEC" >ALUTEC</option>
                    <option value="AMATI" >AMATI</option>
                    <option value="AMERICAN RACING" >AMERICAN RACING</option>
                    <option value="ANTERA" >ANTERA</option>
                    <option value="ANZIO WHEELS" >ANZIO WHEELS</option>
                    <option value="APOLLO" >APOLLO</option>
                    <option value="ARAYS" >ARAYS</option>
                    <option value="ARCASTING" >ARCASTING</option>
                    <option value="ARMY" >ARMY</option>
                    <option value="ARTEC" >ARTEC</option>
                    <option value="ASA WHEELS" >ASA WHEELS</option>
                    <option value="ASANTI" >ASANTI</option>
                    <option value="ASW" >ASW</option>
                    <option value="ATP" >ATP</option>
                    <option value="ATS" >ATS</option>
                    <option value="ATS EXCLUSIVE LINE" >ATS EXCLUSIVE LINE</option>
                    <option value="AUGUST" >AUGUST</option>
                    <option value="AVARUS" >AVARUS</option>
                    <option value="AVENUE" >AVENUE</option>
                    <option value="AVT" >AVT</option>
                    <option value="AVUS" >AVUS</option>
                    <option value="AWS" >AWS</option>
                    <option value="AZ" >AZ</option>
                    <option value="AZEV" >AZEV</option>
                    <option value="BACCARAT" >BACCARAT</option>
                    <option value="BANTAJ" >BANTAJ</option>
                    <option value="BANZAI" >BANZAI</option>
                    <option value="BAOSH" >BAOSH</option>
                    <option value="BARRACUDA" >BARRACUDA</option>
                    <option value="BAZO" >BAZO</option>
                    <option value="BBS" >BBS</option>
                    <option value="BEYERN" >BEYERN</option>
                    <option value="BINNO" >BINNO</option>
                    <option value="BLACK RHINO" >BLACK RHINO</option>
                    <option value="BLADE" >BLADE</option>
                    <option value="BLAQUE" >BLAQUE</option>
                    <option value="BLAQUE DIAMOND" >BLAQUE DIAMOND</option>
                    <option value="BORBET" >BORBET</option>
                    <option value="BRABUS" >BRABUS</option>
                    <option value="BROCK" >BROCK</option>
                    <option value="BSA" >BSA</option>
                    <option value="BTS" >BTS</option>
                    <option value="BWR" >BWR</option>
                    <option value="CAM" >CAM</option>
                    <option value="CARACTERE" >CARACTERE</option>
                    <option value="CARRE" >CARRE</option>
                    <option value="CARWEL" >CARWEL</option>
                    <option value="CATTIVO" >CATTIVO</option>
                    <option value="CATWILD" >CATWILD</option>
                    <option value="CEC WHEELS" >CEC WHEELS</option>
                    <option value="CMS" >CMS</option>
                    <option value="COMPOMOTIVE" >COMPOMOTIVE</option>
                    <option value="CORNICHE SPORTS WHEELS" >CORNICHE SPORTS WHEELS</option>
                    <option value="COVENTRY" >COVENTRY</option>
                    <option value="CRISTA" >CRISTA</option>
                    <option value="CROMODORA" >CROMODORA</option>
                    <option value="CROSS STREET" >CROSS STREET</option>
                    <option value="CW FAHRZEUGTECHNIK" >CW FAHRZEUGTECHNIK</option>
                    <option value="D&P" >D&P</option>
                    <option value="DBL-G" >DBL-G</option>
                    <option value="DBV" >DBV</option>
                    <option value="DELTA DL" >DELTA DL</option>
                    <option value="DELUXE WHEELS" >DELUXE WHEELS</option>
                    <option value="DETATA" >DETATA</option>
                    <option value="DEVINO" >DEVINO</option>
                    <option value="DEZENT" >DEZENT</option>
                    <option value="DIABLO WHEELS" >DIABLO WHEELS</option>
                    <option value="DIAL" >DIAL</option>
                    <option value="DIAMO" >DIAMO</option>
                    <option value="DISLA" >DISLA</option>
                    <option value="DJ WHEELS" >DJ WHEELS</option>
                    <option value="DOTZ" >DOTZ</option>
                    <option value="DRIV" >DRIV</option>
                    <option value="DROPSTARS" >DROPSTARS</option>
                    <option value="DVINCI" >DVINCI</option>
                    <option value="ENKEI" >ENKEI</option>
                    <option value="ENSURE" >ENSURE</option>
                    <option value="ENZO" >ENZO</option>
                    <option value="ETABETA" >ETABETA</option>
                    <option value="EURODISK" >EURODISK</option>
                    <option value="EUROSPORT" >EUROSPORT</option>
                    <option value="F1" >F1</option>
                    <option value="FALKEN" >FALKEN</option>
                    <option value="FLY" >FLY</option>
                    <option value="FONDMETAL" >FONDMETAL</option>
                    <option value="FOR WHEELS" >FOR WHEELS</option>
                    <option value="FORGIATO" >FORGIATO</option>
                    <option value="FORSAGE" >FORSAGE</option>
                    <option value="FR DESIGN" >FR DESIGN</option>
                    <option value="FREEMOTION" >FREEMOTION</option>
                    <option value="FUJIBOND" >FUJIBOND</option>
                    <option value="FUTEK" >FUTEK</option>
                    <option value="GIANELLE" >GIANELLE</option>
                    <option value="GIANNA" >GIANNA</option>
                    <option value="GIOVANNA" >GIOVANNA</option>
                    <option value="GR" >GR</option>
                    <option value="GRAM LIGHTS" >GRAM LIGHTS</option>
                    <option value="GSI" >GSI</option>
                    <option value="HAYES LEMMERZ" >HAYES LEMMERZ</option>
                    <option value="HDS" >HDS</option>
                    <option value="HELO" >HELO</option>
                    <option value="HI-TECH" >HI-TECH</option>
                    <option value="HIPNOTIC WHEELS" >HIPNOTIC WHEELS</option>
                    <option value="IFREE" >IFREE</option>
                    <option value="II CRAVE ALLOYS" >II CRAVE ALLOYS</option>
                    <option value="IJITSU" >IJITSU</option>
                    <option value="IKON WHEELS" >IKON WHEELS</option>
                    <option value="INCUBUS" >INCUBUS</option>
                    <option value="INCURVE WHEELS" >INCURVE WHEELS</option>
                    <option value="INTRA-EXIP" >INTRA-EXIP</option>
                    <option value="ITP" >ITP</option>
                    <option value="IWHEELZ" >IWHEELZ</option>
                    <option value="J&L RACING" >J&L RACING</option>
                    <option value="JANTSA" >JANTSA</option>
                    <option value="JD" >JD</option>
                    <option value="JT" >JT</option>
                    <option value="K&K" >K&K</option>
                    <option value="KAHN" >KAHN</option>
                    <option value="KESKIN TUNING" >KESKIN TUNING</option>
                    <option value="KFZ" >KFZ</option>
                    <option value="KMC" >KMC</option>
                    <option value="KOKO KUTURE" >KOKO KUTURE</option>
                    <option value="KONIG" >KONIG</option>
                    <option value="KORMETAL" >KORMETAL</option>
                    <option value="KOSEI" >KOSEI</option>
                    <option value="KRONPRINZ" >KRONPRINZ</option>
                    <option value="KWM" >KWM</option>
                    <option value="KYOWA" >KYOWA</option>
                    <option value="KYOWA RACING" >KYOWA RACING</option>
                    <option value="L.A. CONNECTION" >L.A. CONNECTION</option>
                    <option value="LAREX" >LAREX</option>
                    <option value="LAWU" >LAWU</option>
                    <option value="LEAGUE" >LEAGUE</option>
                    <option value="LEGEARTIS" >LEGEARTIS</option>
                    <option value="LENSO" >LENSO</option>
                    <option value="LEXANI" >LEXANI</option>
                    <option value="LF DICK" >LF DICK</option>
                    <option value="LORENSO" >LORENSO</option>
                    <option value="LORENZO" >LORENZO</option>
                    <option value="LS WHEELS" >LS WHEELS</option>
                    <option value="LUMARAI" >LUMARAI</option>
                    <option value="M&K" >M&K</option>
                    <option value="MAGLINE" >MAGLINE</option>
                    <option value="MAGNETTO WHEELS" >MAGNETTO WHEELS</option>
                    <option value="MAK" >MAK</option>
                    <option value="MAMBA" >MAMBA</option>
                    <option value="MAMBA OFF ROAD" >MAMBA OFF ROAD</option>
                    <option value="MANDRUS" >MANDRUS</option>
                    <option value="MARCELLO" >MARCELLO</option>
                    <option value="MAXX WHEELS" >MAXX WHEELS</option>
                    <option value="MAZZI" >MAZZI</option>
                    <option value="MEFRO" >MEFRO</option>
                    <option value="MI-TECH" >MI-TECH</option>
                    <option value="MICKEY THOMPSON" >MICKEY THOMPSON</option>
                    <option value="MIM" >MIM</option>
                    <option value="MKW" >MKW</option>
                    <option value="MKW OFF-ROAD" >MKW OFF-ROAD</option>
                    <option value="MML" >MML</option>
                    <option value="MODULAR SOCIETY" >MODULAR SOCIETY</option>
                    <option value="MOMO" >MOMO</option>
                    <option value="MONTE FIORE" >MONTE FIORE</option>
                    <option value="MOTEGI RACING" >MOTEGI RACING</option>
                    <option value="MOTO METAL" >MOTO METAL</option>
                    <option value="MPW" >MPW</option>
                    <option value="MS MOTORSPORTS" >MS MOTORSPORTS</option>
                    <option value="MSW" >MSW</option>
                    <option value="NAKAYAMA" >NAKAYAMA</option>
                    <option value="NEXT" >NEXT</option>
                    <option value="NINGBO" >NINGBO</option>
                    <option value="NITRO" >NITRO</option>
                    <option value="NOLOGO" >NOLOGO</option>
                    <option value="NORDWAY" >NORDWAY</option>
                    <option value="NP-WHEELS" >NP-WHEELS</option>
                    <option value="NZ WHEELS" >NZ WHEELS</option>
                    <option value="OFF-ROAD-WHEELS" >OFF-ROAD-WHEELS</option>
                    <option value="OXIGIN" >OXIGIN</option>
                    <option value="OZ RACING" >OZ RACING</option>
                    <option value="P&W" >P&W</option>
                    <option value="PANTHER" >PANTHER</option>
                    <option value="PDW WHEELS" >PDW WHEELS</option>
                    <option value="PLATINUM" >PLATINUM</option>
                    <option value="PRIMO" >PRIMO</option>
                    <option value="PRO COMP" >PRO COMP</option>
                    <option value="PROMA" >PROMA</option>
                    <option value="PTW" >PTW</option>
                    <option value="R-STEEL" >R-STEEL</option>
                    <option value="R-TEX" >R-TEX</option>
                    <option value="RACE READY" >RACE READY</option>
                    <option value="RACING SPARCO" >RACING SPARCO</option>
                    <option value="RACING WHEELS" >RACING WHEELS</option>
                    <option value="RADIUS" >RADIUS</option>
                    <option value="RAPID" >RAPID</option>
                    <option value="RC DESIGN" >RC DESIGN</option>
                    <option value="RED WHEEL" >RED WHEEL</option>
                    <option value="REDBOURNE" >REDBOURNE</option>
                    <option value="REPLAY" >REPLAY</option>
                    <option value="REPLICA" >REPLICA</option>
                    <option value="REPLIKEY" >REPLIKEY</option>
                    <option value="RIAL" >RIAL</option>
                    <option value="ROMAGNA RUOTE" >ROMAGNA RUOTE</option>
                    <option value="RONAL" >RONAL</option>
                    <option value="RONDELL" >RONDELL</option>
                    <option value="RONER" >RONER</option>
                    <option value="ROSSO" >ROSSO</option>
                    <option value="ROYAL WHEELS" >ROYAL WHEELS</option>
                    <option value="RS WHEELS" >RS WHEELS</option>
                    <option value="RUSSTEC" >RUSSTEC</option>
                    <option value="SAKURA WHEELS" >SAKURA WHEELS</option>
                    <option value="SANFOX" >SANFOX</option>
                    <option value="SANT" >SANT</option>
                    <option value="SCHMIDT" >SCHMIDT</option>
                    <option value="SEBRING" >SEBRING</option>
                    <option value="SEYEN" >SEYEN</option>
                    <option value="SH" >SH</option>
                    <option value="SHARK" >SHARK</option>
                    <option value="SL" >SL</option>
                    <option value="SLIK" >SLIK</option>
                    <option value="SMC" >SMC</option>
                    <option value="SODI WHEELS" >SODI WHEELS</option>
                    <option value="SPARCO WHEELS" >SPARCO WHEELS</option>
                    <option value="SPEEDLINE CORSE" >SPEEDLINE CORSE</option>
                    <option value="SPORTMAX RACING" >SPORTMAX RACING</option>
                    <option value="SPORTWAY" >SPORTWAY</option>
                    <option value="SRD TUNING" >SRD TUNING</option>
                    <option value="SSW" >SSW</option>
                    <option value="STARK" >STARK</option>
                    <option value="STEEL WHEELS" >STEEL WHEELS</option>
                    <option value="STILAUTO" >STILAUTO</option>
                    <option value="STONEWELL" >STONEWELL</option>
                    <option value="STORM WHEELS" >STORM WHEELS</option>
                    <option value="STRUT" >STRUT</option>
                    <option value="STYL" >STYL</option>
                    <option value="SW" >SW</option>
                    <option value="SWIGER" >SWIGER</option>
                    <option value="SWORD" >SWORD</option>
                    <option value="TAILONG" >TAILONG</option>
                    <option value="TANSY WHEELS" >TANSY WHEELS</option>
                    <option value="TEAM DYNAMICS" >TEAM DYNAMICS</option>
                    <option value="TECH-LINE" >TECH-LINE</option>
                    <option value="TEZZEN" >TEZZEN</option>
                    <option value="TGR" >TGR</option>
                    <option value="TGRACING" >TGRACING</option>
                    <option value="TIS" >TIS</option>
                    <option value="TOMASON" >TOMASON</option>
                    <option value="TOORA" >TOORA</option>
                    <option value="TR DESIGN" >TR DESIGN</option>
                    <option value="TREBL" >TREBL</option>
                    <option value="TRW" >TRW</option>
                    <option value="TSW" >TSW</option>
                    <option value="TUNZZO" >TUNZZO</option>
                    <option value="U.S. WHEEL" >U.S. WHEEL</option>
                    <option value="URBAN RACING" >URBAN RACING</option>
                    <option value="VALBREM" >VALBREM</option>
                    <option value="VALENTE" >VALENTE</option>
                    <option value="VAULT" >VAULT</option>
                    <option value="VCT" >VCT</option>
                    <option value="VELOCHE" >VELOCHE</option>
                    <option value="VERDE" >VERDE</option>
                    <option value="VERTINI" >VERTINI</option>
                    <option value="VIANOR" >VIANOR</option>
                    <option value="VICTOR EQUIPMENT" >VICTOR EQUIPMENT</option>
                    <option value="VINDETA" >VINDETA</option>
                    <option value="VMR WHEELS" >VMR WHEELS</option>
                    <option value="VOLK RACING" >VOLK RACING</option>
                    <option value="VOLVO" >VOLVO</option>
                    <option value="VORXTEC" >VORXTEC</option>
                    <option value="WALPAX" >WALPAX</option>
                    <option value="WHEELWORLD" >WHEELWORLD</option>
                    <option value="WIGER" >WIGER</option>
                    <option value="WM" >WM</option>
                    <option value="WOLF" >WOLF</option>
                    <option value="WOLF WHEELS" >WOLF WHEELS</option>
                    <option value="WORK" >WORK</option>
                    <option value="WRC" >WRC</option>
                    <option value="X'TRIKE" >X'TRIKE</option>
                    <option value="X7" >X7</option>
                    <option value="XD SERIES" >XD SERIES</option>
                    <option value="XINFA" >XINFA</option>
                    <option value="XXIO" >XXIO</option>
                    <option value="YAMATO" >YAMATO</option>
                    <option value="YOKATTA" >YOKATTA</option>
                    <option value="YOKATTA RAYS" >YOKATTA RAYS</option>
                    <option value="YOKOHAMA" >YOKOHAMA</option>
                    <option value="YST" >YST</option>
                    <option value="YUELING WHEELS" >YUELING WHEELS</option>
                    <option value="ZD WHEELS" >ZD WHEELS</option>
                    <option value="ZENT" >ZENT</option>
                    <option value="ZEPP" >ZEPP</option>
                    <option value="ZINIK" >ZINIK</option>
                    <option value="ZORAT WHEELS" >ZORAT WHEELS</option>
                    <option value="ZORMER" >ZORMER</option>
                    <option value="ZRACING" >ZRACING</option>
                    <option value="ZUMBO WHEELS" >ZUMBO WHEELS</option>
                    <option value="ВИКОМ" >ВИКОМ</option>
                    <option value="ВСМПО" >ВСМПО</option>
                    <option value="ГАЗ" >ГАЗ</option>
                    <option value="ИЖМАШ" >ИЖМАШ</option>
                    <option value="КАМАЗАВТОТЕХНИКА" >КАМАЗАВТОТЕХНИКА</option>
                    <option value="КРАМЗ" >КРАМЗ</option>
                    <option value="КРЕМЕНЧУГСКИЙ КОЛЁСНЫЙ ЗАВОД" >КРЕМЕНЧУГСКИЙ КОЛЁСНЫЙ ЗАВОД</option>
                    <option value="КУЛЗ" >КУЛЗ</option>
                    <option value="КУМЗ" >КУМЗ</option>
                    <option value="МАГАЛТЕК" >МАГАЛТЕК</option>
                    <option value="МЕГАЛЮМ" >МЕГАЛЮМ</option>
                    <option value="СКАД" >СКАД</option>
                    <option value="СМЗ" >СМЗ</option>
                    <option value="СМК" >СМК</option>
                    <option value="СТОКРАТ" >СТОКРАТ</option>
                    <option value="ТЗСК" >ТЗСК</option>
                    <option value="4 RACING" >4 RACING</option>
                    <option value="4GO" >4GO</option>
                    <option value="57 MOTORSPORT" >57 MOTORSPORT</option>

                </select>
            </div>
        </div>

        <!-- Select Basic -->
        <div class="form-group">
            <div class="col-md-4 col-md-offset-4">
                <input type="submit" class="btn btn-primary" value="Добавить к запросу">
            </div>
        </div>
    </fieldset>
</form>
